//@ sourceMappingURL=app.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['config'], function(cfg) {
    return require(['angular'], function(A) {
      A.module(cfg.ngApp, []);
      return require(['routes']);
    });
  });

}).call(this);
