//@ sourceMappingURL=config.map
// Generated by CoffeeScript 1.6.1
(function() {

  require.config({
    shim: {
      angular: {
        exports: 'angular'
      }
    },
    paths: {
      angular: '../components/angular/angular'
    }
  });

  define([], function() {
    return {
      ngApp: 'tv-app',
      path: {
        partial: 'app/partial/'
      }
    };
  });

}).call(this);
