//@ sourceMappingURL=routes.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['config', 'angular', 'controller/home-controller'], function(cfg, A, HomeController) {
    var app, routes;
    routes = function($routeProvider) {
      $routeProvider.when('/home', {
        controller: HomeController.$name,
        templateUrl: cfg.path.partial + 'home-partial.html'
      });
      return $routeProvider.otherwise({
        redirectTo: '/home'
      });
    };
    routes.$inject = ['$routeProvider'];
    routes.$eager = true;
    app = A.module(cfg.ngApp);
    app.config(routes);
    return A.bootstrap(document, [cfg.ngApp]);
  });

}).call(this);
